name: Python Application CI/CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          echo "requirements.txt not found. This may cause issues." >&2
        fi
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run tests
      run: |
        pytest tests/ || echo "Tests failed, but continuing workflow"
    - name: Build Docker image
      run: |
        docker build -t myapp:${{ github.sha }} .
      continue-on-error: true
    - name: Push to Docker Hub
      run: |
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker push myapp:${{ github.sha }}
      continue-on-error: true
    - name: Deploy to production
      run: |
        ssh user@production-server 'docker pull myapp:${{ github.sha }} && docker stop myapp-container && docker rm myapp-container && docker run -d --name myapp-container myapp:${{ github.sha }}'
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
      continue-on-error: true

    #################################################
    #      KUBIYA BUILD ANALYSIS SECTION
    #################################################

    - name: Capture detailed logs
      if: always()
      run: |
        {

          echo "Event Type: ${{ github.event_name }}"
          echo "Workflow Name: ${{ github.workflow }}"
          echo "Runner OS: ${{ runner.os }}"
          echo "Runner Architecture: ${{ runner.arch }}"

          echo "######## Github ########"
          echo "GITHUB_WORKFLOW: $GITHUB_WORKFLOW"
          echo "GITHUB_ACTION: $GITHUB_ACTION"
          echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "Job: ${{ github.job }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo "Status: ${{ job.status }}"
          echo "Git Tag: ${{ github.ref }}"
          echo "Triggered By: ${{ github.actor }}"
          echo "Branch: ${{ github.ref }}"
          echo "Repository: ${{ github.repository }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Commit Message: ${{ github.event.head_commit.message }}"
          echo "PR Number: ${{ github.event.pull_request.number }}"
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "PR Author: ${{ github.event.pull_request.user.login }}"
          echo "PR Base Branch: ${{ github.event.pull_request.base.ref }}"
          echo "PR Head Branch: ${{ github.event.pull_request.head.ref }}"
          echo "PR URL: ${{ github.event.pull_request.html_url }}"

          echo "######## Tests ########"
          echo "Tests Output: (skipped tests)"

          echo "######## Docker ########"
          echo "Docker version:"
          docker --version
          echo "Docker images:"
          docker images
          echo "######## Pipeline STDOUT ########"
          echo "Step outputs:"
          echo "${{ toJson(steps) }}"
        } > detailed_logs.txt
